# SMS Gateway Docker Compose
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sms_gateway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/app/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/sms_gateway?sslmode=disable
      - PRICE_PER_PART_CENTS=5
      - EXPRESS_SURCHARGE_CENTS=2
      - LOG_LEVEL=info
    depends_on:
      postgres:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/sms_gateway?sslmode=disable
      - PRICE_PER_PART_CENTS=5
      - EXPRESS_SURCHARGE_CENTS=2
      - LOG_LEVEL=info
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: