# Modern Docker Compose (no version needed)

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sms_gateway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  nats:
    image: nats:2-alpine
    ports:
      - "4222:4222"
      - "8222:8222"  # HTTP monitoring
    command: ["-js", "-m", "8222"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/varz"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/sms_gateway?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - PRICE_PER_PART_CENTS=5
      - RATE_LIMIT_RPS=100
      - RATE_LIMIT_BURST=200
      - MOCK_SUCCESS_RATE=0.8
      - MOCK_TEMP_FAIL_RATE=0.15
      - MOCK_PERM_FAIL_RATE=0.05
      - MOCK_LATENCY_MS=100
      - LOG_LEVEL=info
      - METRICS_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    environment:
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/sms_gateway?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - NATS_URL=nats://nats:4222
      - PRICE_PER_PART_CENTS=5
      - MOCK_SUCCESS_RATE=0.8
      - MOCK_TEMP_FAIL_RATE=0.15
      - MOCK_PERM_FAIL_RATE=0.05
      - MOCK_LATENCY_MS=100
      - RETRY_MIN_DELAY=15s
      - RETRY_MAX_DELAY=30m
      - RETRY_FACTOR=2.0
      - MAX_ATTEMPTS=10
      - LOG_LEVEL=info
      - METRICS_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
    deploy:
      replicas: 2  # Run 2 worker instances for redundancy

volumes:
  postgres_data:
  redis_data:
